### ISSUE TITLE
Possible to compile on 10.10.2?

### ISSUE THREAD

**Issue by ninjaprawn** [CharizTeam/Chariz#3]
I know that the new Photos app is on 10.10.3 (which is in beta), but is it possible compile the project on 10.10.2?

**Comment by kirb** [comment]
Your best bet is to find a copy of UXKit.framework somewhere one way or another (surely there's somewhere that's hosting a zip or something of it, even though they really shouldn't be). I've heard UXKit does work on 10.10.[0-2].

**Comment by bd452** [comment]
You can check out my branch for an example that compiles on non-beta
systems.

**Comment by shinvou** [comment]
@bd452 You know that it's illegal to distribute the framework?
